---
- name: Create public ip
  azure_rm_publicipaddress:
    resource_group: DryIce
    allocation_method: Static
    name: "{{ name }}"
    location: eastus2

       
- name: Create NIC
  azure_rm_networkinterface:
    resource_group: DryIce
    name: "{{ name }}"
    virtual_network: DryIce_Hybrid
    subnet: private
    public_ip_name: "{{ name }}"
    security_group: DryIce_Hybrid
    location: eastus2

- name: Create VM with defaults
  azure_rm_virtualmachine:
    resource_group: DryIce
    name: "{{ name }}"
    admin_username: "{{ admin_username }}"
    admin_password: "{{ admin_password }}"
    location: eastus2
    vm_size: "{{ vm_size }}"
    network_interfaces: "{{ name }}"
    image: templatecentos7.5
    tags:
      ing: "env"
