---
- name: Create VM with defaults
  azure_rm_virtualmachine:
    resource_group: DryIce
    name: testvm10
    vm_size: Standard_A3
    state: present 
    admin_username: test
    admin_password: test@1234567890
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.1'
      version: latest
