---
- name: Create a VM with a custom image from a particular resource group
  azure_rm_virtualmachine:
    resource_group: ing_resource
    name: testvm001
    vm_size: Standard_DS1_v2
    admin_username: adminUser
    admin_password: password01
    image:
      name: ingawxclient-image-20191005182301
      resource_group: ing_resource
