---
- name: Create public ip
  azure_rm_publicipaddress:
    resource_group: DryIce
    allocation_method: Static
    name: "{{ name }}"
    location: eastus2

- name: Create security group that allows SSH
  azure_rm_securitygroup:
    resource_group: DryIce
    name: "{{ name }}"
    location: eastus2
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 101
        direction: Inbound
      - name: HTTP
        protocol: Tcp
        destination_port_range: 80
        access: Allow
        priority: 102
        direction: Inbound
      - name: HTTPS
        protocol: Tcp
        destination_port_range: 443
        access: Allow
        priority: 103
        direction: Inbound
        
- name: Create NIC
  azure_rm_networkinterface:
    resource_group: DryIce
    name: "{{ name }}"
    virtual_network: DryIce_Hybrid
    subnet: PublicSubnet1
    public_ip_name: "{{ name }}"
    security_group: "{{ name }}"
    location: eastus2

- name: Create VM with defaults
  azure_rm_virtualmachine:
    resource_group: DryIce
    name: "{{ name }}"
    admin_username: "{{ admin_username }}"
    admin_password: "{{ admin_password }}"
    location: eastus2
    vm_size: Standard_A1
    network_interfaces: "{{ name }}"
    image: templatecentos7.5
